### ISSUE TITLE
MingGW tool box error 

### ISSUE THREAD

**Issue by CyanW0202** [msys2/MSYS2-packages-dev#2]
Hi, I was trying to use this command:
 pacman -S --needed base-devel mingw-w64-x86_64-toolchain
from https://www.msys2.org/ , to finihsh up the configuration.

However,  there is a warning for an email to be an unknow trust, and couple corrupt files at the first place and eventually failed me.
It says "no package is updated." so I went on and update them with the tutorial https://www.msys2.org/docs/updating/ .

I come back and download the tool box again, but it seems like duplicated files are slowing down my laptop dramatically.
But I got the complier working eventually.

Just wonder how can I clean up the duplication files in this case. Does $ paccache -r work?

**Comment by Biswa96** [comment]
We are not in correct repository. But anyway, did you run `pacman -Syyu` **twice** before that command?
